server:
  port: 9295
spring :
  application :
    name : hystrix-dashboard
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    hostname : localhost
    serviceUrl :
      defaultZone : http://localhost:8761/eureka/
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"